/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:341ea8f0-1771-4314-a701-9ac6463dd95b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Z7kqmsNd5",
    "aws_user_pools_web_client_id": "1dh48oq7h897atfbgu3oq49adi",
    "oauth": {
        "domain": "quiccasaclient2fae62b4-2fae62b4-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/oauth2/,https://quiccasa.sistemisolari.com/oauth2/",
        "redirectSignOut": "http://localhost:3000/oauth2-out/,https://quiccasa.sistemisolari.com/oauth2-out/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
